spring.application.name=Banking

spring.datasource.url=${DB_URL:jdbc:mysql://146.148.103.183:3306/dev_db?connectTimeout=10000&socketTimeout=30000&tcpKeepAlive=true}
spring.datasource.username=${DB_USERNAME:usr_dev}
spring.datasource.password=${DB_PASSWORD:Dev#Pass2026$}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
